/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "var(--color-surface-dim)",
        "on-secondary-fixed": "#291800",
        "on-background": "var(--color-text)",
        "surface-container-high": "var(--color-surface-high)",
        "primary-container": "#2e7d32",
        "on-secondary-fixed-variant": "#633f00",
        "tertiary-fixed": "#ffdad6",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed-variant": "#005312",
        "background": "var(--color-bg)",
        "inverse-on-surface": "#f1f1ec",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface": "var(--color-surface)",
        "primary": "#0d631b",
        "on-secondary-container": "#6b4500",
        "surface-container-low": "var(--color-surface-low)",
        "on-error-container": "#93000a",
        "surface-container-lowest": "var(--color-card-bg)",
        "outline-variant": "var(--color-border)",
        "on-error": "#ffffff",
        "secondary-container": "#feae2c",
        "inverse-surface": "#2f312e",
        "surface-container-highest": "#e3e3de",
        "surface-container": "var(--color-surface-container)",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ac",
        "on-tertiary-fixed": "#410003",
        "on-surface": "var(--color-text)",
        "surface-variant": "var(--color-surface-container)",
        "on-tertiary": "#ffffff",
        "surface-tint": "#1b6d24",
        "on-tertiary-container": "#ffedeb",
        "secondary-fixed-dim": "#ffb955",
        "on-tertiary-fixed-variant": "#930010",
        "surface-bright": "var(--color-bg)",
        "on-surface-variant": "var(--color-text-muted)",
        "secondary": "#835500",
        "tertiary-container": "#d02d2d",
        "tertiary": "#ac0c18",
        "on-primary-container": "#cbffc2",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffddb4",
        "on-primary-fixed": "#002204",
        "inverse-primary": "#88d982",
        "primary-fixed": "#a3f69c",
        "outline": "#707a6c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
